import { useMemo, useState, type CSSProperties } from "react";
import { zipSync, strToU8 } from "fflate";
import { deleteAllPhotos, deletePhoto, newId, savePhoto } from "../../data/store";
import { resolveDateComparePhotos, updateDateCompareSelection, validateProgressPhoto, type PhotoViewerState } from "../../domain/photo-selection";
import { Button, Empty, Field, Sheet } from "../../ui/components";
import { useApp } from "../../ui/context";
import { localDateKey } from "../../domain/dates";
import { PhotoImage, PhotoViewer } from "./PhotoViewer";

function FileChoice({ label, capture, disabled, onFile }: { label: string; capture?: "environment"; disabled: boolean; onFile: (file?: File) => void }) {
  return <label className="button secondary file-choice">{label}<input type="file" accept="image/jpeg,image/png,image/webp" capture={capture} disabled={disabled} onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; onFile(file); }} /></label>;
}

export function ProgressPhotos() {
  const { data, run, busy } = useApp();
  const photos = useMemo(() => [...data.photos].sort((a, b) => a.date.localeCompare(b.date) || (a.capturedAt ?? 0) - (b.capturedAt ?? 0)), [data.photos]);
  const [date, setDate] = useState(localDateKey(Date.now())), [month, setMonth] = useState(localDateKey(Date.now()).slice(0, 7)), [filterDate, setFilterDate] = useState<string>(), [compareMode, setCompareMode] = useState(false), [compare, setCompare] = useState<[string | undefined, string | undefined]>([undefined, undefined]), [viewer, setViewer] = useState<PhotoViewerState>(), [clear, setClear] = useState(false), [addForDay, setAddForDay] = useState<string>();
  const [year, monthNumber] = month.split("-").map(Number), first = new Date(year, monthNumber - 1, 1), dayCount = new Date(year, monthNumber, 0).getDate(), comparePhotos = resolveDateComparePhotos(photos, ...compare), visible = filterDate ? photos.filter((photo) => photo.date === filterDate) : photos;
  const add = async (candidate?: File) => { const file = validateProgressPhoto(candidate); if (!file) return; await savePhoto({ id: newId(), date, capturedAt: Date.now(), notes: "", blob: file }); };
  const download = (bytes: Uint8Array, name: string, type: string) => { const url = URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer], { type })), link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
  const exportAll = async () => { const files: Record<string, Uint8Array> = {}; const used = new Set<string>(); for (const photo of photos) { const ext = photo.blob.type === "image/png" ? "png" : photo.blob.type === "image/webp" ? "webp" : "jpg"; let name = `photo_${photo.date}_${photo.id}.${ext}`; while (used.has(name)) name = `copy_${name}`; used.add(name); files[name] = new Uint8Array(await photo.blob.arrayBuffer()); } files["notes.json"] = strToU8(JSON.stringify(photos.map(({ id, date, capturedAt, notes }) => ({ id, date, capturedAt, notes })), null, 2)); download(zipSync(files, { level: 6 }), "ironlog_progress_photos.zip", "application/zip"); };
  const shareLatest = async () => { const latest = photos.at(-1); if (!latest) return; const file = new File([latest.blob], `ironlog_${latest.date}.jpg`, { type: latest.blob.type }); if (navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) await navigator.share({ title: "IronLog progress", files: [file] }); else download(new Uint8Array(await latest.blob.arrayBuffer()), file.name, file.type); };
  const shiftMonth = (amount: number) => { const next = new Date(year, monthNumber - 1 + amount, 1); setMonth(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}`); };
  return <><header className="native-screen-title"><span className="eyebrow">Body composition</span><h1>Progress photos</h1><p>Stored only in this browser. Web ZIP backups retain the image bytes.</p></header>
    <section className="card photo-calendar-card"><div className="photo-month-nav"><Button variant="ghost" onClick={() => shiftMonth(-1)} aria-label="Previous month">‹</Button><strong>{first.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</strong><Button variant="ghost" onClick={() => shiftMonth(1)} aria-label="Next month">›</Button></div><div className="calendar-weekdays" aria-hidden="true">{["M", "T", "W", "T", "F", "S", "S"].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}</div><div className="photo-calendar" style={{ "--first-day": ((first.getDay() + 6) % 7) + 1 } as CSSProperties}>{Array.from({ length: dayCount }, (_, index) => index + 1).map((day) => { const key = `${month}-${String(day).padStart(2, "0")}`, has = photos.some((photo) => photo.date === key), selected = compare.includes(key) || filterDate === key; return <button key={key} aria-label={`${has ? compareMode ? "Compare" : "Filter" : "Add photo for"} ${key}${has ? ", has photo" : ""}`} aria-pressed={selected} className={`${has ? "has-photo" : ""} ${selected ? "selected" : ""}`} onClick={() => { if (!has) { setDate(key); setAddForDay(key); } else if (compareMode) setCompare((current) => updateDateCompareSelection(...current, key)); else { setFilterDate((current) => current === key ? undefined : key); setDate(key); } }}><span>{day}</span>{has && <i />}</button>; })}</div>{photos.length > 0 && <small>{compareMode ? "has photo · tap two dates to compare" : "has photo · tap to filter"}</small>}</section>
    <div className="photo-mode-tabs"><Button variant={!compareMode ? "primary" : "ghost"} onClick={() => { setCompareMode(false); setCompare([undefined, undefined]); }}>Filter day</Button><Button variant={compareMode ? "primary" : "ghost"} onClick={() => { setCompareMode(true); setFilterDate(undefined); }}>Compare dates</Button></div>{compareMode && <p className="muted">{!compare[0] ? "Tap a date with a photo to set compare slot A." : !compare[1] ? "Tap a second date to build the comparison." : "Comparing the latest photo from each selected date."}</p>}
    <section className="card"><Field label="Photo date"><input type="date" max={localDateKey(Date.now())} value={date} onChange={(event) => setDate(event.target.value)} /></Field><div className="two-col"><FileChoice label="Camera" capture="environment" disabled={busy} onFile={(file) => void run(() => add(file), "Photo saved")} /><FileChoice label="From device" disabled={busy} onFile={(file) => void run(() => add(file), "Photo saved")} /></div></section>
    {photos.length > 0 && <div className="inline-actions"><Button variant="ghost" disabled={busy} onClick={() => void run(shareLatest)}>Share latest</Button><Button variant="ghost" disabled={busy} onClick={() => void run(exportAll, "Photo archive exported")}>Export all</Button><Button variant="danger" disabled={busy} onClick={() => setClear(true)}>Clear all</Button>{filterDate && <Button variant="ghost" onClick={() => setFilterDate(undefined)}>Clear filter</Button>}</div>}
    {comparePhotos[0] && comparePhotos[1] && <section className="card"><h2>Before & after</h2><div className="photo-compare">{comparePhotos.map((photo) => photo && <PhotoImage key={photo.id} photo={photo} onClick={() => setViewer({ kind: "compare", ids: [comparePhotos[0]!.id, comparePhotos[1]!.id] })} />)}</div></section>}
    {!visible.length ? <Empty title={filterDate ? "No photos on this date" : "No progress photos yet"}><p>Choose a date and add a camera or library photo.</p></Empty> : <div className="photo-grid">{[...visible].reverse().map((photo) => <section key={photo.id} className="photo-entry"><PhotoImage photo={photo} onClick={() => setViewer({ kind: "single", ids: [photo.id] })} /><Button variant="danger" onClick={() => run(() => deletePhoto(photo.id), "Photo deleted")}>Delete photo from {photo.date}</Button></section>)}</div>}
    {viewer && <PhotoViewer state={viewer} photos={photos} onClose={() => setViewer(undefined)} />}{addForDay && <Sheet title={`Add photo for ${addForDay}`} onClose={() => setAddForDay(undefined)}><p>Choose how to add a photo for this date.</p><FileChoice label="Camera" capture="environment" disabled={busy} onFile={(file) => void run(() => add(file), "Photo saved").then((ok) => { if (ok) setAddForDay(undefined); })} /><FileChoice label="Gallery" disabled={busy} onFile={(file) => void run(() => add(file), "Photo saved").then((ok) => { if (ok) setAddForDay(undefined); })} /></Sheet>}{clear && <Sheet title="Clear all progress photos?" onClose={() => setClear(false)}><p>This permanently removes every stored photo and note from this browser.</p><Button variant="danger" disabled={busy} onClick={() => void run(deleteAllPhotos, "All progress photos deleted").then((ok) => { if (ok) { setClear(false); setCompare([undefined, undefined]); setFilterDate(undefined); } })}>Clear all photos</Button></Sheet>}
  </>;
}
