import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'db_smoke_tests',
      columns: [
        { name: 'label', type: 'string' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'exercises',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'normalized_name', type: 'string', isIndexed: true },
        { name: 'primary_muscle', type: 'string', isIndexed: true },
        { name: 'equipment', type: 'string', isIndexed: true },
        { name: 'category', type: 'string' },
        { name: 'is_custom', type: 'boolean', isIndexed: true },
        { name: 'source', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'exercise_muscles',
      columns: [
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'muscle', type: 'string', isIndexed: true },
        { name: 'role', type: 'string' },
        { name: 'contribution_fraction', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'plans',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'goal', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'plan_days',
      columns: [
        { name: 'plan_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'order_index', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'plan_exercises',
      columns: [
        { name: 'plan_day_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'order_index', type: 'number' },
        { name: 'sets', type: 'number' },
        { name: 'reps', type: 'string' },
        { name: 'rest_seconds', type: 'number' },
        { name: 'superset_group', type: 'string', isOptional: true },
        { name: 'is_warmup', type: 'boolean' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'workouts',
      columns: [
        { name: 'plan_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'plan_day_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'started_at', type: 'number', isIndexed: true },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'duration_seconds', type: 'number' },
        { name: 'rating', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'workout_exercises',
      columns: [
        { name: 'workout_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'order_index', type: 'number' },
        { name: 'superset_group', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'workout_sets',
      columns: [
        { name: 'workout_exercise_id', type: 'string', isIndexed: true },
        { name: 'set_index', type: 'number' },
        { name: 'weight', type: 'number' },
        { name: 'reps', type: 'number' },
        { name: 'rpe', type: 'number', isOptional: true },
        { name: 'rir', type: 'number', isOptional: true },
        { name: 'rest_seconds', type: 'number' },
        { name: 'is_warmup', type: 'boolean' },
        { name: 'is_dropset', type: 'boolean' },
        { name: 'is_amrap', type: 'boolean' },
        { name: 'to_failure', type: 'boolean' },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'body_measurements',
      columns: [
        { name: 'measured_at', type: 'number', isIndexed: true },
        { name: 'bodyweight', type: 'number', isOptional: true },
        { name: 'waist', type: 'number', isOptional: true },
        { name: 'chest', type: 'number', isOptional: true },
        { name: 'arm', type: 'number', isOptional: true },
        { name: 'thigh', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'app_settings',
      columns: [
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
        { name: 'value_type', type: 'string' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'progress_photos',
      columns: [
        { name: 'file_uri', type: 'string' },
        { name: 'taken_at', type: 'number', isIndexed: true },
        { name: 'bodyweight', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
